config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :students 
  devise_for :admins

  
  get 'admins/students_list' => 'admins#students_list', as: :students_list
  get 'admins/upgrade' => 'admins#upgrade', as: :upgrade
  get 'admins/sign_in' => 'pages#home'
  delete 'admins/sign_out' => 'devise/sessions#destroy'
  resources :admins

  get 'students/sing_in' => 'pages#home'
  delete 'students/sign_out' => 'devise/sessions#destroy'
  resources :students
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :first_student_id, class_name: Student
  belongs_to :second_student_id, class_name: Student

  validates :first_student_id, presence: true
  validates :second_student_id, presence: true



end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :student

  validates :name, presence: true

end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, presence: true, uniqueness: true, length: { maximum: 50}
  validates :name, presence: true, uniqueness: true, length: { maximum: 50}
  validates :password, presence: true, length: { minimum: 6}

  def change_status
  	update_columns(admin: admin ? false : true)
  end

 end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

	def index
		@students = Student.select(:name).map(&:name)
		@teams = RoundRobinTournament.schedule(@students)
	end

	def students_list
		@students = Student.all
	end

	def upgrade
		@students = Student.all
		@student = Student.find(params[:student_id])
		@student.change_status

		render :students_list
	end

	private

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  

  private

  def after_sign_in_path_for(resource)
    if resource == :student
      new_student_session_path
    elsif resource == :admin
      students_list_path
    else
      root_path
    end
  end


  def after_sign_out_path_for(resource_or_scope)
    	root_path
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def index
    students = Student.select(:name).map(&:name)
    @teams = RoundRobinTournament.schedule(students)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :set_profile, only: [:edit, :update]
	before_action :authenticate_user!

	def new
		@prodile =Profile.new
	end

	def create
		@profile = current_student.build_profile(profile_params)

		if @profile.save
			redirect_to edit_profile_path(@profile), notice: "Name added!"
		else
			render :new
		end
	end
	def edit
	end

	def update
		if @profile.update(profile_params)
			redirect_to edit_profile_path(@profile), notice: "Name updated!"
		else
			render :edit
		end
	end

	private

	def set_profile
		@profile = current_student.profile
	end

	def profile_params
		params.require(:profile).permit(:name)
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

	def upgrade
		student = Student.find(params[:id])
		if student.upgrade( :admin => true )
			redirect_to admins_path
		else
			render 'edit'
		end
	end

	private

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/admins/index.html.erb
<h1>Matches<strong>Overview</strong>:</h1>
<hr>
<br>

<% @teams.each_with_index do |day, index| %>
		<% day_teams = day.map { |team| "(#{team.first}, #{team.last})" }.join(', ') %>

		<% concat "Day #{index + 1}: #{day_teams}" %>
		<br>
		<br>
		<br>
	<% end %>

app/views/admins/students_list.html.erb
<div class='main'>
<h1>Students<strong>List</strong></h1>
<hr>
<br>
<% @students.each do |student| %>
<%= student.name %> 

<button class="btn-up">
	<% if !student.admin? %>
		<%= link_to 'Upgrade', upgrade_path(student_id: student.id) %>
	<% else %>
		<%= link_to 'Downgrade', upgrade_path(student_id: student.id) %>
	<% end %>
</button>

<br>
<% end %>
</div>

app/views/layouts/application.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<link href="https://fonts.googleapis.com/css?family=Bubbler+One" rel="stylesheet">
<body>
  <!-- Static navbar -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "YourDailyMatch", root_path, class: "navbar-brand" %>

    </div>
    <div class="nav navbar-nav logged">
      <% if student_signed_in? %>
          <li><h4> You are logged as a<strong> Student</strong></h4></li>
          <% elsif admin_signed_in? %>
          <li><h4> You are logged as an<strong> Admin</strong></h4></li>
          <% else %>
        
          <% end %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <%= render 'shared/navbar' %>   
    </ul>
  </div>
</nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
    <%= yield %>
  </div>
</body>

app/views/matches/index.html.erb
<% @teams.each_with_index do |day, index| %>
<% day_teams = day.map { |team| "(#{team.first}, #{team.last})" }.join(", ")%>

<% concat "Day #{index + 1}: #{day_teams}" %> <hr>
<% end %>

app/views/pages/home.html.erb
<% if student_signed_in? %>
<%= render 'students/show-today-match' %>
<% elsif admin_signed_in? %>
<div class="welcome">
<h1> You're so welcome!</h1>
<br>
<%= link_to "Generate", admins_path, class: "generate" %>
</div>
<% else %>
<div class="welcome">
<h1>Your<strong>Daily</strong>Match</h1>
<h2> You're so welcome! </h2>
</div>
<% end %>

app/views/shared/_admin.html.erb
<li><%= link_to "Overview", admins_path %></li>
<li><%= link_to "StudentList", students_list_path %></li>
<li></li>
<li><%= link_to "Log out", destroy_admin_session_path, method: :delete %>

app/views/shared/_navbar.html.erb
<% if current_student.present? %>
	<% if current_student.admin %> 
		<li><%= link_to "Overview", admins_path %></li>
		<li><%= link_to "StudentList", students_list_path %></li>
	<% end %>
	<li><%= link_to "Log out", destroy_student_session_path, method: :delete %></li>
<% elsif current_admin.present? %> 
	<li><%= link_to "Overview", admins_path %></li>
	<li><%= link_to "StudentList", students_list_path %></li>
	<li><%= link_to "Log out", destroy_admin_session_path, method: :delete %>
<% else %> 
	<li><%= link_to "☞ SignUp", new_student_registration_path, class: "glyphicon" %></li>
	<li><%= link_to "☆ LoginAsStudent", new_student_session_path, class: "glyphicon" %></li>
	<li><%= link_to "★ LoginAsAdmin", new_admin_session_path, class: "glyphicon" %></li>
<% end %> 

app/views/shared/_student.html.erb
      <li><%= link_to "Log out", destroy_student_session_path, method: :delete %></li>

app/views/students/_show-today-match.html.erb
<h1>Your<strong>Day</strong>Match:</h1>


		<% render concat "Day #{@index + 1}#{day_teams}" %>